title: Tumble Network
url: https://tumblenet.github.io/beta.tumblenet.cu.cc/
logo-url: /images/logo.png
permalink: /blog/:categories/:year/:month/:day/:title/
disqus-shortname: tumble-network-beta
excerpt_separator: <!--more-->
exclude: [vendor]
mobile-nav-on-desktop: true
collections:
  team:
    output: true
  carousel:
